backend:
  name: github
  repo: matulich7-star/mcstudio-web
  branch: main
  site_domain: mcstudio.cl
  base_url: https://snetter.vercel.app
  auth_endpoint: /api/auth

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "proyectos"
    label: "Proyectos / Portafolio"
    folder: "content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Principal", name: "thumbnail", widget: "image", required: false }
      - { label: "Descripción / Detalles", name: "body", widget: "markdown" }
