backend:
  name: github
  repo: matulich7-star/mcstudio-web
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "blog"
    label: "Blog / Proyectos"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Cuerpo de texto", name: "body", widget: "markdown" }
