backend:
  name: github
  repo: matulich7-star/mcstudio-web
  branch: main
  base_url: https://decap-oauth.vercel.app
  auth_endpoint: /api/auth

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "proyectos"
    label: "Proyectos"
    folder: "content/proyectos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Imagen Principal", name: "thumbnail", widget: "image", required: false }
      - { label: "Descripcion", name: "body", widget: "markdown" }
